### ISSUE TITLE
Handle sharing of pre-trained models

### ISSUE THREAD

**Issue by SalamanderXing** [ilex-paraguariensis/yerbamate#35]
We need a way to share pre-trained models, which are pretty large files. Unfortunately, we cannot force people to share them, but we can provide a hosting solution that handles that. We will probably need two commands (at least):
- `mate login`
- `mate deploy`

**Comment by oalee** [comment]
I'm afraid at this stage we do not have resources to host the files ourselves, we should consider using third party APIs such as google buckets, weight and biases or huggingface.
Ideally we should use torrent to host everything, data and pretrained models, but to kickstart the torrent we still need a seedbox server.

**Comment by oalee** [comment]
> But don't we have re-upload all the model weights in both cases? Both if we changed the model and if we changed the weights? Anyways maybe we could continue this in its own [issue](https://github.com/ilex-paraguariensis/yerbamate/issues/35).

Yes we need to reupload, and let the user know there has been an update and a need for re-download if desired
