### ISSUE TITLE
`model.py` file should be replaced by a section in the hyperparameters file.

### ISSUE THREAD

**Issue by SalamanderXing** [ilex-paraguariensis/yerbamate#36]
We are currently using the file `model.py` inside the model as a configuration file. It would be better if we handled that inside our hyperparameter json file. This way we would have two kinds of components: models and training components. Models are PyTorch models and training components are Lightning. Training components take as hyperparameter which models to use. Having this distinction will allow for better exploration of hyperparameters but also will allow us to install these. Train and models components should be installed differently.

**Comment by oalee** [comment]
We could have something like this:
```
{
     ...
     "train": "Regression" or "MyRegrssion" // Regression can be a base mate class that expects "generator"
     "model":{
     "classifier":"ResNet",
     "generator": "ResNetAutoEncoder"
     }
}
```

**Comment by SalamanderXing** [comment]
Yes, that looks good. 
Also, (but I need to thing better about this) the cool thing about doing that is that mate could handle turning "ResNet" into .components.resnet.Resnet for example. So we could make sure there are no dependencies outside that model folder.

**Comment by oalee** [comment]
Yes! This way we could handle Type class imports.

For selecting the lightning class, we need to know two things, the file name and the class name. We could as a convention use the class name of `Model`, or specify in the json file the class name. I think the first option is better, we should try to keep the hyperparameters as small as possible.

**Comment by oalee** [comment]
First version works with parameters such as the following, the "model" is a python file that should have a `Model` class.

```
    "train": "model",
    "model": {
        "classifier": {
            "module": "modules.conv2d.resnet",
            "model": "ResNetClassifier"
        }
    },
```

After running this for the first time, parameters of the model will get populated:
```
    "model": {
        "classifier": {
            "module": "modules.conv2d.resnet",
            "model": "ResNetClassifier",
            "params": {
                "in_features": 165,
                "h_embedding": 1,
                "num_blocks": [
                    4,
                    4,
                    4,
                    4
                ],
                "c_hidden": [
                    64,
                    128,
                    256,
                    512
                ],
                "in_channel": 13,
                "num_classes": 1
            }
        }
    },
```

**Comment by oalee** [comment]
Todos:

- [ ] Handling of parameters that do not have default values
- [ ] Update add dependency functionality to work with this design

For the first todo, we can't do much except generate parameters in the json with empty strings or 0s, and ask the user to correct the parameters.
