### ISSUE TITLE
Modelsaver parameters

### ISSUE THREAD

**Issue by oalee** [ilex-paraguariensis/yerbamate#42]
Currently model saver parameters are hardcoded in Mate class, should become a part of hyperparameters

**Comment by oalee** [comment]
Model saver has bugs due to a pytorch bug, this and the bug in ModelSaver cannot be fixed before pytorch 1.2.1 is released.

**Comment by SalamanderXing** [comment]
I fixed it temporarily using a simple torch save.

**Comment by oalee** [comment]
restarting now works with pytorch 1.2.1,
If you encounter issues with cuda as I did, install pytorch with this: 
```
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
```

**Comment by oalee** [comment]
ModelCheckpoint parameters now are read from the json file, e.g
```
    "model_checkpoint": {
        "save_top_k": 1,
        "save_last": true,
        "verbose": true,
        "monitor": "val_loss",
        "mode": "min"
    },
```

For now, restarting looks for "last.ckpt", and test looks for "best.ckpt" and "save_last" should always be true.
