### ISSUE TITLE
Logs directory weights a disproportionate amount 

### ISSUE THREAD

**Issue by SalamanderXing** [ilex-paraguariensis/yerbamate#44]
Lightning automatically fills the logs directory with so much staff that for a simple projects it weights 9.8G!

**Comment by oalee** [comment]
Its not exactly a bug, more of a feature 😄

We can't change what Tensorboard does, and probably every log is saved without any compression so after various experiments you have a lot of logs. We should look into wandab logger, its popular and uploads to a cloud, which might be more size efficient.

**Comment by oalee** [comment]
I am closing this issue since now you can select any logger.
