### ISSUE TITLE
Implementing base model (task agnostic)

### ISSUE THREAD

**Issue by SalamanderXing** [ilex-paraguariensis/yerbamate#6]
With save features (like performances) and best model. Maybe call it MateModel?

**Comment by oalee** [comment]
Well save features depend on the returns of `on_validation_epoch_end` or `train_step` and etc. This could be specified in parameters. Something like  this:
```{
"save_statistics" :{
"interval": 100,
"values": ["loss", "accuracy", "f1"]
}
```

The first use case that I think of our base model is automatically assigning the optimizers from parameters, so you don't need to write any boilerplate code.
I think simply BaseModel is enough, `from mate import BaseModel`
